#!/usr/bin/env ruby
require_relative 'mob_rotation'


file_name = ARGV[0]
command = ARGV[1]
mobster_names = ARGV[2..-1]

# start_time 
#time = Time.now
#last_rotation = File.mtime(file_name)
#rotation_time = last_rotation + 120

mob_rotator = MobRotator.new(file_name)
# time_to_rotate if time > rotation_time

case command
when nil
  mob_rotator.show_mobsters
when "rotate"
  mob_rotator.rotate
  mob_rotator.show_mobsters
when "add"
  mob_rotator.add_mobster(*mobster_names)
  mob_rotator.show_mobsters
when "remove"
  mob_rotator.remove_mobsters(*mobster_names)
  mob_rotator.show_mobsters
when "help"
  mob_rotator.show_help
else
  mob_rotator.inform_lovely_user(command)
end

