#!/usr/bin/env ruby
require_relative 'mob_rotation'


file_name = ARGV[0]
command = ARGV[1]
mobster_name = ARGV[2]

# start_time 
#time = Time.now
#last_rotation = File.mtime(file_name)
#rotation_time = last_rotation + 120

mob_rotator = MobRotator.new(file_name)
# time_to_rotate if time > rotation_time
mob_rotator.rotate if command == "rotate"
mob_rotator.add_mobster(mobster_name) if command == "add"
mob_rotator.show_mobsters()