#!/usr/bin/env ruby
require_relative 'mob_rotation'

file_name = ARGV[0] || 'rotate.txt'
command = ARGV[1]
mobster_names = ARGV[2..-1]
git_dir = ENV['MOB_GIT_DIR'] || File.join(Dir.pwd, ".git")

mob_rotator = MobRotation.new(Database.new(file_name), git_dir)
mob_rotator.command_router(command, mobster_names)
